name: CI/CD

on:
  push:
    branches:
      - lab7
  pull_request:
    branches:
      - lab7

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'
      - run: flutter pub get
      - run: flutter analyze --no-fatal-warnings --no-fatal-infos

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'
      - run: flutter pub get
      - run: flutter test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'
      - run: flutter pub get
      - run: flutter build web --release

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'
      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
